apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv
  labels:
    type: local
spec:
  storageClassName: standart
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  # persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/mnt/influxdb"