apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
spec:
  storageClassName: standart
  volumeName: influxdb-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi