apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: influxdb
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8086
    targetPort: 8086
---

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: influxdb-pv
#   labels:
#     type: local
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   hostPath:
#     path: "/mnt/influxdb"
---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: influxdb-pvc
#   # labels:
#     # app: influxdb
# spec:
#   storageClassName: standart
#   volumeName: influxdb-pv
#   accessModes:
#   - ReadWriteOnce
#   # volumeMode: Filesystem
#   resources:
#     requests:
#       storage: 500Mi
# ---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb
          image: amayor_influxdb_image
          imagePullPolicy: Never
          ports:
          - containerPort: 8086
          volumeMounts:
          - name: docker-socket
            mountPath: /var/run/docker.sock
          - name: influxdb-data
            mountPath: /root/.influxdbv2
          env:
          - name: INFLUX_HOST
            value: http://localhost:8086
          - name: INFLUX_TOKEN
            valueFrom:
              secretKeyRef:
                name: influxdb-secret
                key: influxdb_token
          - name: INFLUXDB_USER
            valueFrom:
              secretKeyRef:
                name: influxdb-secret
                key: influxdb_user
          - name: INFLUXDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: influxdb-secret
                key: influxdb_password
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: influxdb-data
        persistentVolumeClaim:
          claimName: influxdb-pvc