apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  # labels:
    # app: influxdb
spec:
  storageClassName: standart
  volumeName: influxdb-pv
  accessModes:
  - ReadWriteOnce
  # volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi