apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: amayor_mysql_image
          imagePullPolicy: Never
          ports:
          - containerPort: 3306
          volumeMounts:
          - name: mysql-data
            mountPath: /var/lib/mysql
          env:
          - name: USER_NAME
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-user-name
          - name: USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-user-password
          - name: DB_NAME
            value: wordpress
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
